ante: 5
blind_structure: null
initial_stack: 1000
max_round: 100
small_blind: 10
ai_players:
- name: honest_AI
  path: /src/pypokergui/Config/players/honest_player.py

- name: PokerShark
  path: /src/pypokergui/Config/players/remote_player.py
