#!/bin/bash

docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.10-management 2> /dev/null

if [[ "$(docker images -q poker_gui 2> /dev/null)" == "" ]]; then
  echo "[-] Image not found..."
  echo "[+] Building image..."
  docker rmi poker_gui -f
  cd PyPokerGUI
  docker build -t poker_gui .
  cd ..
fi


(sleep 2 && xdg-open http://localhost:8888) &
docker run -it --rm --name=poker_gui_test -v $(pwd)/Config:/app -p 8888:8000 poker_gui
