ante: 0
blind_structure: null
initial_stack: 1000
max_round: 100
small_blind: 10
ai_players:

- name: Bold
  path: /src/config/players/bold_player.py

- name: PokerShark
  path: /src/config/players/remote_player.py
